import { afterEach, beforeEach, describe, expect, it, vi } from 'vitest'
import type { AppData, Habit } from '~/types/app-data'
import { APP_DATA_SCHEMA_VERSION, COLLECTION_LIMITS, DEFAULT_SETTINGS } from '~/types/app-data'
import {
  backupFilename,
  describeImportOutcome,
  extractImportedHabits,
  mergeHabitsForImport,
  serializeBackup,
} from '~/utils/persistence/backup'
import type { ParseAppDataResult } from '~/utils/persistence/storage-schema'

function validHabit(overrides: Partial<Habit> = {}): Habit {
  return {
    id: 'h1',
    name: 'Read',
    type: 'build',
    identityStatement: 'Reader',
    scheduleWeekdays: [1],
    reminderTime: '08:00',
    startDate: '2026-02-01',
    archived: false,
    pauses: [],
    createdAt: '2026-02-01T00:00:00.000Z',
    updatedAt: '2026-02-01T00:00:00.000Z',
    ...overrides,
  }
}

function emptyAppData(overrides: Partial<AppData> = {}): AppData {
  return {
    schemaVersion: APP_DATA_SCHEMA_VERSION,
    habits: [],
    entries: [],
    suggestions: [],
    settings: { ...DEFAULT_SETTINGS },
    ...overrides,
  }
}

describe('extractImportedHabits (#69)', () => {
  it('returns habits from a full-backup envelope', () => {
    const backup = emptyAppData({ habits: [validHabit({ id: 'full_1', name: 'From backup' })] })
    const habits = extractImportedHabits(backup)
    expect(habits.map(h => h.id)).toEqual(['full_1'])
    expect(habits[0]?.name).toBe('From backup')
  })

  it('accepts a bare habits array via the lenient path', () => {
    const raw = [
      { name: 'Walk', type: 'build', identityStatement: 'Walker', scheduleWeekdays: [1, 2] },
      { name: 'No sugar', type: 'break', identityStatement: 'Healthy', scheduleWeekdays: [0] },
    ]
    const habits = extractImportedHabits(raw)
    expect(habits).toHaveLength(2)
    expect(habits[0]?.name).toBe('Walk')
    // Missing ids are generated by the lenient schema.
    expect(habits[0]?.id).toMatch(/^habit_/)
  })

  it('accepts a { habits: [...] } wrapper via the lenient path', () => {
    const raw = { habits: [{ name: 'Walk', type: 'build', identityStatement: 'Walker', scheduleWeekdays: [1] }] }
    expect(extractImportedHabits(raw)).toHaveLength(1)
  })

  it('drops invalid habits and keeps valid ones', () => {
    const raw = [
      { name: 'Valid', type: 'build', identityStatement: 'Ok', scheduleWeekdays: [1] },
      { name: '', type: 'build', identityStatement: 'Missing name', scheduleWeekdays: [1] },
      { name: 'Bad type', type: 'nope', identityStatement: 'x', scheduleWeekdays: [1] },
      { name: 'No days', type: 'build', identityStatement: 'x', scheduleWeekdays: [] },
    ]
    const habits = extractImportedHabits(raw)
    expect(habits.map(h => h.name)).toEqual(['Valid'])
  })

  it('returns [] when there is no habits-array shape', () => {
    expect(extractImportedHabits(42)).toEqual([])
    expect(extractImportedHabits({ notHabits: [] })).toEqual([])
    expect(extractImportedHabits(null)).toEqual([])
  })

  it('throws (surfacing the raw preflight) when the raw habit list exceeds the cap (#35)', () => {
    const raw = Array.from({ length: COLLECTION_LIMITS.habits + 1 }, () => ({ id: 'dup' }))
    expect(() => extractImportedHabits(raw)).toThrow()
  })

  it('throws when a raw habit has an over-limit nested pauses array (#35)', () => {
    const raw = [
      {
        name: 'X',
        type: 'build',
        identityStatement: 'x',
        scheduleWeekdays: [1],
        pauses: new Array(COLLECTION_LIMITS.pausesPerHabit + 1),
      },
    ]
    expect(() => extractImportedHabits(raw)).toThrow()
  })
})

describe('mergeHabitsForImport (#69)', () => {
  beforeEach(() => {
    vi.useFakeTimers()
    vi.setSystemTime(new Date('2026-07-15T12:00:00.000Z'))
  })

  afterEach(() => {
    vi.useRealTimers()
  })

  it('appends brand-new habits and counts them as added', () => {
    const existing = [validHabit({ id: 'a' })]
    const imported = [validHabit({ id: 'b', name: 'New' })]
    const { mergedHabits, addedCount, updatedCount } = mergeHabitsForImport(existing, imported)
    expect(mergedHabits.map(h => h.id)).toEqual(['b', 'a'])
    expect(addedCount).toBe(1)
    expect(updatedCount).toBe(0)
  })

  it('updates an existing habit by id, preserving createdAt and stamping updatedAt', () => {
    const existing = [validHabit({ id: 'a', name: 'Old', createdAt: '2020-01-01T00:00:00.000Z' })]
    const imported = [validHabit({ id: 'a', name: 'Renamed', createdAt: '2099-01-01T00:00:00.000Z' })]
    const { mergedHabits, addedCount, updatedCount } = mergeHabitsForImport(existing, imported)
    expect(addedCount).toBe(0)
    expect(updatedCount).toBe(1)
    const merged = mergedHabits.find(h => h.id === 'a')
    expect(merged?.name).toBe('Renamed')
    expect(merged?.createdAt).toBe('2020-01-01T00:00:00.000Z')
    expect(merged?.updatedAt).toBe('2026-07-15T12:00:00.000Z')
  })

  it('keeps existing habits that are not in the import', () => {
    const existing = [validHabit({ id: 'a' }), validHabit({ id: 'b' })]
    const imported = [validHabit({ id: 'a', name: 'Updated' })]
    const { mergedHabits } = mergeHabitsForImport(existing, imported)
    expect(mergedHabits.map(h => h.id).sort()).toEqual(['a', 'b'])
  })

  it('dedupes imported habits by id (last write wins)', () => {
    const imported = [validHabit({ id: 'a', name: 'First' }), validHabit({ id: 'a', name: 'Second' })]
    const { mergedHabits, addedCount } = mergeHabitsForImport([], imported)
    expect(mergedHabits).toHaveLength(1)
    expect(mergedHabits[0]?.name).toBe('Second')
    expect(addedCount).toBe(1)
  })

  it('does not mutate the input arrays', () => {
    const existing = [validHabit({ id: 'a' })]
    const imported = [validHabit({ id: 'a', name: 'Renamed' })]
    mergeHabitsForImport(existing, imported)
    expect(existing[0]?.name).toBe('Read')
  })
})

describe('describeImportOutcome (#68)', () => {
  it('reports a clean ok result as a generic success', () => {
    const result: ParseAppDataResult = { status: 'ok', data: emptyAppData(), sourceVersion: APP_DATA_SCHEMA_VERSION }
    expect(describeImportOutcome(result)).toEqual({
      ok: true,
      title: 'Import complete',
      description: 'Backup data has been restored.',
    })
  })

  it('notes the schema upgrade for a migrated result', () => {
    const result: ParseAppDataResult = { status: 'migrated', data: emptyAppData(), sourceVersion: 1, steps: ['v1->v2'] }
    const outcome = describeImportOutcome(result)
    expect(outcome.ok).toBe(true)
    expect(outcome.title).toBe('Import complete')
    expect(outcome.description).toContain('Upgraded from schema v1')
  })

  it('gives actionable copy for an unsupported (newer) version', () => {
    const result: ParseAppDataResult = { status: 'unrecoverable', reason: 'unsupported-version', message: 'x', sourceVersion: 99 }
    const outcome = describeImportOutcome(result)
    expect(outcome.ok).toBe(false)
    expect(outcome.title).toBe('Import failed')
    expect(outcome.description).toContain('newer version of the app')
  })

  it('gives generic invalid-file copy for other unrecoverable reasons', () => {
    for (const reason of ['invalid-shape', 'oversized', 'migration-failed'] as const) {
      const result: ParseAppDataResult = { status: 'unrecoverable', reason, message: 'x', sourceVersion: undefined }
      const outcome = describeImportOutcome(result)
      expect(outcome.ok, reason).toBe(false)
      expect(outcome.description, reason).toBe('The file is not valid AppData JSON.')
    }
  })
})

describe('serializeBackup / backupFilename (#69)', () => {
  it('serializes to pretty-printed JSON that round-trips', () => {
    const data = emptyAppData({ habits: [validHabit()] })
    const json = serializeBackup(data)
    expect(json).toContain('\n  ')
    expect(JSON.parse(json)).toEqual(data)
  })

  it('builds a dated filename', () => {
    expect(backupFilename('2026-08-24')).toBe('habit-tracker-2026-08-24.json')
  })
})
